version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/html:/var/www/html:ro
    depends_on:
      - app
    ports:
      - ${PORT}:80
    networks:
      default:
      internal:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: capoost-app
    user: app
    environment:
    - PORT=8000
    - SESSIONNAME=session
    - DBSERVICE=postgres
    - DBNAME=
    - DBUSER=
    - DBPASSWD=
    - DBHOST=db
    - DBPORT=5432
    depends_on:
    - db
    entrypoint: "bash -c 'sleep 5 && ./bin/capoost'"
    networks:
      internal:
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=
    networks:
      internal:

networks:
  default:
    ipam:
      config:
      - subnet: ${SUBNET0}
  internal:
    ipam:
      config:
      - subnet: ${SUBNET1}
    internal: true
